# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97e91118696cd34c7ba4665afcc451b4e9978318f5b4f3bd2a4d23dfb1b0c4757bfa022f49b1eda12b549efdac55e142d6ee0749608eff5486c32daa7cfb112b

test:
  secret_key_base: 5d126558d01534cc39a9eee22543c7b20ae1bdf32f783cf1a64d1fa7d5b247d87aea13c519b2938f00130b407d5870353727f31c9082249a46e9b6c2fac8ddd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
